### ISSUE TITLE
High timings for placeholder requests

### ISSUE THREAD

**Issue by leogianfagna** [titanlabs-mc/battle-pass#618]
### Describe the bug

_I know I'm not on latest version (I'm 4.7.9) but the new versions just added new features to the plugin._

Creating placeholderapi quests is causing lag to the server. Here is a spark for it: https://spark.lucko.me/P3S8Ee6WsB

### How to reproduce

Create some placeholder quests, like:
type: placeholderapi_integer_xltournaments_escavar_score
type: placeholderapi_integer_VotingPlugin_Total_Daily_process

It is possible to this high usage for each quest:
![image](https://github.com/user-attachments/assets/97cf1869-1774-48ac-835b-4d70d54e54c0)

### Screenshots / Videos

Above

**Comment by KPGTB** [comment]
Hey! Our plugin consumes only 0.5% of server thread so it's not that much. Also I don't see any lags on your spark. Problem which you mentioned is mostly caused by plugin which adds that placeholder (probably mycommands) which executes sql every request, but as I said, 0.5% is not that much and it shouldn't cause any performance problems
